<?php
if(isset($_POST["Image"], $_POST["FileName"], $_GET["Name"])){
    $upload_dir = "..\\..\\uploads\\";
    $is_dir = is_dir($upload_dir);
    $is_writeable = is_writable($upload_dir);
    
    if($is_dir && $is_writeable){
        $data = get_image_data_from_js_base64($_POST["Image"]);
        
        $file = $upload_dir.$_GET["Name"]."_".$_POST["FileName"];
        $file = str_replace(" ", "_", $file);
        
        $success = file_put_contents($file, $data);
        $uploaded = !($success === false);
    }else{
        $uploaded = false;
    }
    
    if($uploaded){
        echo "Successfully uploaded.";
    }else{
        echo "Upload unsuccessful.";
    }
}

function get_image_data_from_js_base64($image_data){
    // split base 64 encoded string around data boundary
    $split_img = explode(";base64,", $image_data);
    // get just the image data
    $base64img = $split_img[1];
    // base 64 strings generated by javascript must
    // have ' ' replaced with '+' or they will be
    // considered corrupt by php
    $base64img = str_replace(" ", "+", $base64img);
    $data = base64_decode($base64img);
    return $data;
}

?>